name: Modelops deploy

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:
    runs-on: ubuntu-latest
#    container: adsoft/aiops:latest

    steps:
    - uses: actions/checkout@v2
    - name: hello-world
      run: echo "hello world workflows …"
    - name: show python version
      run: python --version
    - name: install modules
      run: pip install -r requirements.txt
    - name: show dir
      run: ls -la
    - name: execute model
      run: python /linear_model.py

